spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: yo_key
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://178.250.156.180:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect